"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { PreferencesProvider } from "@/context/PreferencesContext";
import { DataProvider } from "@/context/DataContext";
import { VideoProvider } from "@/context/VideoContext";

import CameraPermission from "@/components/CameraPermission";
import { GA_TRACKING_ID, pageview } from "../utils/gtag";
import { usePathname } from "next/navigation";
import { ReactNode, useEffect } from "react";
import Script from "next/script";

import { GoogleAnalytics } from "@next/third-parties/google";

const inter = Inter({ subsets: ["latin"] });

export default function Layout({ children }: { children: ReactNode }) {
  const pathname = usePathname();
  useEffect(() => {
    if (!window.GA_INITIALIZED) {
      window.GA_INITIALIZED = true;
    }
    pageview(pathname);
  }, [pathname]);
  return (
    <html lang="en">
      <head>
        <title>Solo Eater</title>
        <meta name="description" content="Generated by create next app" />
        {/* <Script
          strategy="afterInteractive"
          src={`https://www.googletagmanager.com/gtag/js?id=${GA_TRACKING_ID}`}
        />
        <Script
          id="ga-script"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', '${GA_TRACKING_ID}', {
                page_path: window.location.pathname,
              });
            `,
          }}
        /> */}
      </head>
      <GoogleAnalytics gaId={`${GA_TRACKING_ID}`} />
      <body className={inter.className}>
        <DataProvider>
          <PreferencesProvider>
            {/* <VideoProvider> */}
            {children}
            <CameraPermission />
            {/* </VideoProvider> */}
          </PreferencesProvider>
        </DataProvider>
      </body>
    </html>
  );
}
